import { AxiosResponse } from 'axios'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { fetchArticles, fetchCategories } from '../api'
import ArticleList from '../components/ArticleList'
import Tabs from '../components/Tabs'
import { IArticle, IArticleAttributes, ICategory, ICollectionResponse } from '../types'

interface IPropTypes {
    categories: {
        items: ICategory[];
    };
    articles:{
      items:IArticle[]
    }

}

const Home:NextPage<IPropTypes> =({categories,articles})=> {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Tabs categories={categories.items}  />
       <ArticleList articles={articles.items}/>
    </>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
 //articles

   const{
    data:articles
   }:AxiosResponse<ICollectionResponse<IArticleAttributes[]>> = await fetchArticles()

  //categories
 console.log("articles",articles)
    const {
        data: categories,
    }: AxiosResponse<ICollectionResponse<ICategory[]>> =
        await fetchCategories();

  console.log("categories",categories);
  return{
    props:{
      categories:{
        items: categories.data
      },
      articles:{
        items:articles.data,
        pagination:articles.meta.pagination
      }
    }
  }
  
}